spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:tcp://localhost/~/testdb
    initialization-mode: always
    platform: h2
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

